apiVersion: v1
kind: Service
metadata:
  name: react-web-app
  namespace: desarrollo
spec:
  type: NodePort
  selector:
    app: react-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
